# **Naive-Bayes**

**- Definisi :**

Algoritma Naive Bayes adalah algoritma yang mempelajari probabilitas suatu objek dengan ciri-ciri tertentu yang termasuk dalam kelompok atau kelas tertentu.

**- Algoritam Naive-Bayes :**
1. Menghitung jumlah kelas / label,
2. Menghitung Jumlah Kasus Per Kelas,
3. Kalikan Semua Variable Kelas,
4. Bandingkan Hasil Per Kelas.
**- Implementasi :**


Memecah antara datatraining dan datatest

In [ ]:
from sklearn.model_selection import train_test_split

Mengimport paket pandas dan paket numpy

In [ ]:
import pandas as pd
import numpy as np

Mengimport library yang dibutuhkan

In [ ]:
# library for Naive Bayes Gaussian
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder

#Model Select
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

Menghilangkan warning

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

Mengambil dataset iris pada github

In [ ]:
dataset_url = "https://raw.githubusercontent.com/RibutDwiArtah023/datamining/main/IRIS.csv"

Menampilkan 5 data teratas dari dataset

In [ ]:
df = pd.read_csv(dataset_url)
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Melihat baris (banyak data) dan kolom (banyak atribut/fitur)

In [ ]:
df.shape

(150, 5)

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
X=iris.data
y=iris.target

Menampilkan dataframe dengan data training tanpa label kelas dari setiap data

In [ ]:
X = df.drop(columns=["species"]) #Mengecek apakah label kelas sudah terhapus
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

Menentukan jumlah data tes/uji yang akan diambil (dalam bentuk persen). Data uji yang akan diambil sebanyak 30%

In [ ]:
# percent_amount_of_test_data = / HUNDRED_PERCENT
percent_amount_of_test_data = 0.3

Melakukan Train Test Split untuk membagi dataset menjadi training set (data latih) dan test set (data uji/tes). 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = percent_amount_of_test_data, random_state=0)

In [ ]:
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0])

In [ ]:
#Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
gaussian = GaussianNB()

# Memasukkan data training pada fungsi klasifikasi naive bayes
gaussian.fit(X_train, y_train)

#Menentukan hasil prediksi dari x_test
Y_pred = gaussian.predict(X_test) 

accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

#melakukan confussion matrix 
cm = confusion_matrix(y_test, Y_pred)

#melihat nilai akurasi, presisi, dan recall dari algoritma naive bayes 
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_random_Forest : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
accuracy_Naive Bayes: 1.000
precision_Naive Bayes: 1.000
recall_Naive Bayes: 1.000
f1-score_random_Forest : 1.000


In [ ]:
# separate target 

# values
X=df.iloc[:,0:4].values

# classes
y=df.iloc[:,4].values

In [ ]:
clf = GaussianNB()
clf.fit(X, y)
clf_pf = GaussianNB()
clf_pf.partial_fit(X, y, np.unique(y))

GaussianNB()

Pengujian data uji


In [ ]:
# uji coba dengan data [5.5, 3, 5, 2.2]
print(clf_pf.predict([[5.5, 3, 5, 2.2]]))


['Iris-virginica']


In [ ]:
# uji coba dengan data [4, 3, 5, 1.2]
print(clf_pf.predict([[4, 3, 5, 1.2]]))


['Iris-versicolor']
